// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type PostMutation struct {
	Create *Post `json:"create"`
}

type PostQuery struct {
	Posts []*Post `json:"posts"`
}

type Query struct {
}
